
title: Minecraft-Wiki

# Description de votre site
description: Un court wiki sur la ville d'Albi, son histoire et son patrimoine.

# Nom de l'auteur ou des contributeurs
author: Votre Nom

# URL de base de votre site
url: "https://votrenom.github.io"  # Remplacez par l'URL de votre dépôt

# Thème à utiliser (vous pouvez changer 'minima' par un autre thème)
theme: hacker

# Autres configurations facultatives
# Permet d'utiliser des plugins, de définir des paramètres personnalisés, etc.
plugins:
  - jekyll-feed  # Permet d'ajouter un flux RSS
